account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
    path('signout/', views.signout, name='signout'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('settings/', views.settings_page, name='settings'),
    path('change.avatar/', views.select_avatar, name='select_avatar'),
    path('send_correction/', views.send_correction, name='send_correction'),
    path('activate/<uidb64>/<token>', views.activate_email, name='activate'),

    path('password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset_form.html',
            email_template_name='account/password/password_reset_email.html',
            success_url = reverse_lazy('account:password_reset_done')
        ),
        name='password_reset'
    ),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password/password_reset_complete.html'), name='password_reset_complete')
]

gallery/urls.py
from django.urls import path, include

from . import views

app_name = 'gallery'

urlpatterns = [
    # views.IndexView.as_view()
    # https://docs.djangoproject.com/en/5.2/intro/tutorial04/
    path('', views.browse, name='browse'),
    path('my', views.browse_my, name='browse_my'),
    path('reviews', views.browse_reviews, name='browse_reviews'),
    path('popular', views.browse_popular, name='browse_popular')
]

mgr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from django.conf.urls.static import static

from photo.views import upload

urlpatterns = [
    # it could be (route, view), but it's better
    # to have separate urls for that
    path('photo/', include("photo.urls")),
    path('account/', include("account.urls")),
    path('gallery/', include("gallery.urls")),
    path('admin/', admin.site.urls),
    path('', upload)
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from . import views

app_name = 'photo'

urlpatterns = [
    path('', views.upload, name='upload'),
    path('<uuid:uuid>/toggle_privacy/', views.toggle_photo_privacy, name='toggle_photo_privacy'),
    path('<uuid:uuid>/toggle_review/', views.toggle_review, name='toggle_review'),
    path('<uuid:uuid>/post_review/', views.post_review, name='post_review'),
    path('<uuid:uuid>/delete', views.delete_photo, name="delete_photo"),
    path('<uuid:uuid>/rename', views.rename_photo, name="rename_photo"),
    path('<uuid:uuid>/location', views.set_location, name="set_location"),
    path('<int:review_id>/helpful/', views.toggle_helpful, name='toggle_helpful'),
    path('<int:review_id>/delete/', views.delete_review, name='delete_review'),
    path('<uuid:uuid>/', views.photo_detail, name="photo_detail")
]

gallery/models.py
from django.db import models

# Create your models here.

gallery/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Page, Paginator

from photo.models import Photo
from animals import animals_pl_map

app_name = 'gallery'
animals_pl_map = {k: v for k, v in sorted(animals_pl_map.items(), key=lambda item: item[1])}

def add_display_name_to_photos(page_obj: Page) -> Page:
    for photo in page_obj:
        animal_name = photo.custom_name if photo.custom_name else photo.prediction
        photo.display_name = animals_pl_map.get(animal_name)
    return page_obj

def browse(request):
    """
    View for browsing images of other users
    """
    photos = Photo.objects.filter(is_private=False).order_by('-upload_time')
    paginator = Paginator(photos, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    page_obj = add_display_name_to_photos(page_obj)
    
    return render(request, "gallery/browse.html", {
        "page_obj": page_obj
    })

@login_required
def browse_my(request):
    """
    View for browsing photos of the user
    """
    photos = Photo.objects.filter(owner=request.user.id).order_by('-upload_time')
    paginator = Paginator(photos, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    page_obj = add_display_name_to_photos(page_obj)
    
    return render(request, "gallery/browse.html", {
        "page_obj": page_obj
    })

@login_required
def browse_reviews(request):
    """
    View for browsing to be reviewed photos
    """
    photos = Photo.objects.filter(is_private=False, review_status=1)
    paginator = Paginator(photos, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    page_obj = add_display_name_to_photos(page_obj)
    
    return render(request, "gallery/browse.html", {
        "page_obj": page_obj
    })

def browse_popular(request):
    """
    View for browsing images of other users
    """
    photos = Photo.objects.filter(is_private=False).order_by('-n_times_seen')
    paginator = Paginator(photos, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    page_obj = add_display_name_to_photos(page_obj)
    
    return render(request, "gallery/browse.html", {
        "page_obj": page_obj
    })

gallery/templates/gallery/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl" data-theme="light">
<head>
    <meta charset="UTF-8" />
    <title>Galeria</title>
    <link rel="stylesheet" href="{% static 'gallery/css/output.css' %}" />
    <link rel="stylesheet" href="{% static 'gallery/css/lazy-image.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/png" href='/media/favicon.png' />
</head>

<body class="body-main">

{% block content %}
{% endblock %}

<div class="dock">
    <button onclick="location.href='{% url 'gallery:browse' %}'" class="{% if request.resolver_match.url_name == 'browse' or request.resolver_match.url_name == 'browse_my' or request.resolver_match.url_name == 'browse_reviews' %}dock-active{% endif %}">
        <svg class="size-[1.8em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="currentColor" stroke-linejoin="miter" stroke-linecap="butt"><polyline points="1 11 12 2 23 11" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="2"></polyline><path d="m5,13v7c0,1.105.895,2,2,2h10c1.105,0,2-.895,2-2v-7" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2"></path><line x1="12" y1="22" x2="12" y2="18" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2"></line></g></svg>
    </button>

    <button onclick="location.href='{% url 'photo:upload' %}'" class="{% if request.resolver_match.url_name == 'upload' %}dock-active{% endif %}">
        <svg class="size-[1.8em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="currentColor" stroke-linejoin="miter" stroke-linecap="butt"><polyline points="3 14 9 14 9 17 15 17 15 14 21 14" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="2"></polyline><rect x="3" y="3" width="18" height="18" rx="2" ry="2" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2"></rect></g></svg>
    </button>

    <button onclick="location.href='{% url 'account:settings' %}'" class="{% if request.resolver_match.url_name == 'settings' %}dock-active{% endif %}">
        <svg class="size-[1.8em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="currentColor" stroke-linejoin="miter" stroke-linecap="butt"><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2"></circle><path d="m22,13.25v-2.5l-2.318-.966c-.167-.581-.395-1.135-.682-1.654l.954-2.318-1.768-1.768-2.318.954c-.518-.287-1.073-.515-1.654-.682l-.966-2.318h-2.5l-.966,2.318c-.581.167-1.135.395-1.654.682l-2.318-.954-1.768,1.768.954,2.318c-.287.518-.515,1.073-.682,1.654l-2.318.966v2.5l2.318.966c.167.581.395,1.135.682,1.654l-.954,2.318,1.768,1.768,2.318-.954c.518.287,1.073.515,1.654.682l.966,2.318h2.5l.966-2.318c.581-.167,1.135-.395,1.654-.682l2.318.954,1.768-1.768-.954-2.318c.287-.518.515-1.073.682-1.654l2.318-.966Z" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2"></path></g></svg>
    </button>
</div>

<script>
    document.addEventListener("DOMContentLoaded", () => {
        document.querySelectorAll(".lazy-image").forEach(img => {
            const parent = img.parentElement;

            function markAsLoaded() {
                parent.classList.add("loaded");
                img.classList.add("loaded");
            }

            // 1️⃣ If image is already loaded (from cache)
            if (img.complete && img.naturalHeight !== 0) {
                markAsLoaded();
            } else {
            // 2️⃣ If still loading, wait for load event
                img.addEventListener("load", markAsLoaded);
            }
        });
    });
</script>

</body>
</html>

gallery/templates/gallery/browse.html
{% extends 'gallery/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}
<div class="browse-container items-top mb-18">
    <div role="tablist" class="tabs tabs-lift tabs-lg justify-center mb-4 flex flex-wrap">
        <a role="tab tab-xl" class="w-1/2 sm:w-auto {% if request.resolver_match.url_name == 'browse_my' %}tab tab-active{% else %}tab{% endif %}" href="{% url 'gallery:browse_my' %}">Moje</a>
        <a role="tab" class="w-1/2 sm:w-auto {% if request.resolver_match.url_name == 'browse' %}tab tab-active{% else %}tab{% endif %}" href="{% url 'gallery:browse' %}">Społeczność</a>
        <a role="tab" class="w-1/2 sm:w-auto {% if request.resolver_match.url_name == 'browse_reviews' %}tab tab-active{% else %}tab{% endif %}" href="{% url 'gallery:browse_reviews' %}">Do weryfikacji</a>
        <a role="tab" class="w-1/2 sm:w-auto {% if request.resolver_match.url_name == 'browse_popular' %}tab tab-active{% else %}tab{% endif %}" href="{% url 'gallery:browse_popular' %}">Najpopularniejsze</a>
    </div>

    {% if page_obj %}
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-4">
            {% for photo in page_obj %}
                <a class="text-center text-2xl" href="{% url 'photo:photo_detail' photo.uuid %}">
                    <div class="card bg-base-100 shadow-sm w-full">
                        <figure>
                            {% thumbnail photo.image "500x282" crop="center" quality=85 as im %}
                                <div class="image-wrapper">
                                    <img src="{{ im.url }}" loading="lazy" alt="Zdjęcie zwierzątka" class="lazy-image" onload="this.classList.add('loaded')"/>
                                </div>
                            {% endthumbnail %}
                            {% if photo.review_status == 1 %}
                                <img src="/media/question_mark.png" class="absolute -top-2 -right-2 w-16 h-16 object-contain"/>
                            {% endif %}
                        </figure>
                        <div class="justify-between p-4 flex items-center">
                            <div class="text-lg">{{ photo.display_name }}</div>
                            <div class="text-stone-500 text-sm">{{ photo.upload_time|date:"j.n.Y, G:i" }}</div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>

        <div class="flex flex-col items-center">
            <span class="mb-1">Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}</span>
            
            <div class="join flex">
                {% if page_obj.has_previous %}
                <a class="join-item btn btn-outline w-24" href="?page={{ page_obj.previous_page_number }}">Poprzednia</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="join-item btn btn-outline w-24" href="?page={{ page_obj.next_page_number }}">Następna</a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <p>Brak zdjęć</p>
    {% endif %}
</div>
{% endblock %}