mgr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from django.conf.urls.static import static

from photo.views import upload

urlpatterns = [
    # it could be (route, view), but it's better
    # to have separate urls for that
    path('photo/', include("photo.urls")),
    path('account/', include("account.urls")),
    path('gallery/', include("gallery.urls")),
    path('admin/', admin.site.urls),
    path('', upload)
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from . import views

app_name = 'photo'

urlpatterns = [
    path('', views.upload, name='upload'),
    path('<uuid:uuid>/toggle_privacy/', views.toggle_photo_privacy, name='toggle_photo_privacy'),
    path('<uuid:uuid>/toggle_review/', views.toggle_review, name='toggle_review'),
    path('<uuid:uuid>/post_review/', views.post_review, name='post_review'),
    path('<uuid:uuid>/delete', views.delete_photo, name="delete_photo"),
    path('<uuid:uuid>/rename', views.rename_photo, name="rename_photo"),
    path('<uuid:uuid>/location', views.set_location, name="set_location"),
    path('<int:review_id>/helpful/', views.toggle_helpful, name='toggle_helpful'),
    path('<int:review_id>/delete/', views.delete_review, name='delete_review'),
    path('<uuid:uuid>/', views.photo_detail, name="photo_detail")
]

photo/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

import uuid


def upload_to_uuid(instance, filename):
    extension = filename.split('.')[-1]
    return f'photos/{instance.uuid}.{extension}'


class Photo(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    upload_time = models.DateTimeField(auto_now_add=True, null=True)
    is_private = models.BooleanField(default=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to=upload_to_uuid, null=True)

    prediction = models.TextField()
    prediction_confidence = models.FloatField()
    prediction_2 = models.TextField(default='empty')
    prediction_confidence_2 = models.FloatField(default=0)
    bbox = models.TextField(null=True)

    review_status = models.PositiveSmallIntegerField(default=0)
    custom_name = models.TextField(null=True)
    localization_latitude = models.FloatField(null=True)
    localization_longitude = models.FloatField(null=True)
    n_times_seen = models.IntegerField(default=0)

    def __str__(self):
        return 'Photo of id: ' + str(self.uuid)

    def get_absolute_url(self):
        return reverse("photo:photo_detail", kwargs={"uuid": self.uuid})


class Review(models.Model):
    upload_time = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    review = models.TextField()
    helpful = models.BooleanField(default=False)

photo/forms.py
from django import forms
from PIL import Image

from .models import Photo

MAX_FILE_SIZE = 1e7

class SendPhotoForm(forms.Form):
    image_file = forms.ImageField(
        label="",
        required=True,
        widget=forms.ClearableFileInput()
    )
    is_private = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput()
    )

    def clean_image_file(self):
        image = self.cleaned_data.get('image_file')
        if image:
            # check size of a file
            if image.size > MAX_FILE_SIZE:
                raise forms.ValidationError("Plik jest za duży. Maksymalnie 10 MB")

            # check type of a file
            try:
                img = Image.open(image)
                img.verify()
            except:
                raise forms.ValidationError("Podany plik nie jest odpowiednim plikiem obrazu")
            
            image.seek(0)

        return image

class PostReviewForm(forms.Form):
    review = forms.CharField(
        widget=forms.TextInput(attrs={'rows': 2, 'placeholder': 'Komentarz'}),
        label=""
    )

photo/views.py
import logging
import os
import json
from io import BytesIO

import requests
from PIL import Image
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponse, HttpResponseBadRequest
from django.core.files.base import ContentFile

from account.models import Correction

from .models import Photo, Review
from .forms import SendPhotoForm, PostReviewForm
from .helpers import add_noise_to_localization
from animals import animals_list, animals_pl_map


logger = logging.getLogger(__name__)
animals_pl_map = {k: v for k, v in sorted(animals_pl_map.items(), key=lambda item: item[1])}


def convert_image_to_webp(uploaded_file) -> ContentFile:
    img = Image.open(uploaded_file)
    img = img.convert("RGB")  # Compatibility (e.g. for PNGs with alpha)
    img.thumbnail((2000, 2000))

    buffer = BytesIO()
    img.save(buffer, format='WEBP', quality=85)

    webp_filename = f"{os.path.splitext(uploaded_file.name)[0]}.webp"

    return ContentFile(buffer.getvalue(), name=webp_filename)


def upload(request):
    """
    A site to upload and classify a photo.
    """
    if request.method == "POST":
        form = SendPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            # convert to webp
            image_webp = convert_image_to_webp(form.cleaned_data['image_file'])
            image_object = None

            # The classification is done on a separate server via API
            try:
                url = "http://localhost:8006/predict"

                image_webp.seek(0)
                files = {"image": (image_webp.name, image_webp.read(), "image/webp")}

                # the request
                response = requests.post(url, files=files, timeout=30)
                if not response.ok:
                    raise Exception(f"Error, status: {response.status_code}")
                response = response.json()

                image_object = Photo.objects.create(
                    is_private=form.cleaned_data['is_private'],
                    image=image_webp,
                    owner=request.user if request.user.is_authenticated else None,
                    prediction='',
                    prediction_confidence=0,
                    review_status=1
                )
                if response.get('category') != 1:
                    image_object.prediction = 'empty'
                else:
                    detected_animal = response.get('detected_animal')
                    bbox = response.get('bbox')
                    confidence = response.get('confidence')
                    image_object.prediction = detected_animal
                    image_object.prediction_confidence = confidence
                    print('here#####################')
                    image_object.prediction_2 = response.get('detected_animal_2')
                    image_object.prediction_confidence_2 = response.get('confidence_2')
                    image_object.bbox = json.dumps(bbox)
                    if confidence > 0.9:
                        image_object.review_status = 0
                image_object.save()
            except Exception as e:
                photo_path = None
                if image_object:
                    photo_path = image_object.image.path
                    image_object.delete()
                if photo_path:
                    if os.path.exists(photo_path):
                        os.remove(photo_path)
                logger.exception(f"Image upload error: {repr(e)}")
                if "Error, status:" in repr(e):
                    return render(request, "photo/upload.html", {"form": form, "error": repr(e)})
                return render(request, "photo/upload.html", {"form": form, "error": f"Nie można połączyć się z serwerem."})

            return redirect(image_object)
    else:
        form = SendPhotoForm()
    return render(request, "photo/upload.html", {"form": form})


def photo_detail(request, uuid):
    """
    Site to display details of a photo
    """
    photo = get_object_or_404(Photo, uuid=uuid)

    if photo.is_private and photo.owner != request.user:
        return HttpResponse('Unauthorized', status=401)

    photo.n_times_seen = photo.n_times_seen + 1
    photo.save()

    post_review_form = PostReviewForm()
    reviews = Review.objects.filter(photo=photo)

    photo.prediction_confidence = photo.prediction_confidence * 100
    photo.prediction_confidence_2 = photo.prediction_confidence_2 * 100

    photo_display_name = photo.custom_name if photo.custom_name else photo.prediction
    photo_display_name = animals_pl_map.get(photo_display_name)
    prediction_display_name = animals_pl_map.get(photo.prediction)
    prediction_display_name_2 = animals_pl_map.get(photo.prediction_2)

    if photo.bbox:
        bbox = json.loads(photo.bbox)
        bbox = [element * 100 for element in bbox]
    else:
        bbox = [0, 0, 0, 0]

    return render(request, "photo/details.html", {
        "photo": photo,
        "photo_display_name": photo_display_name,
        "prediction_display_name": prediction_display_name,
        "prediction_display_name_2": prediction_display_name_2,
        "post_review_form": post_review_form,
        "reviews": reviews,
        'animals_map': animals_pl_map.items(),
        'bbox': bbox
    })


@login_required
def delete_photo(request, uuid):
    """
    View that handles photo deletion
    Deletes photo from database, disk and reviews associated
    """
    photo = get_object_or_404(Photo, uuid=uuid)
    # delete photo from disk
    photo_path = photo.image.path
    if os.path.exists(photo_path):
        os.remove(photo_path)
    # from database
    photo.delete()
    # reviews are deleted automatically, because of CASCADE

    return redirect('gallery:browse_my')


@login_required
def toggle_photo_privacy(request, uuid):
    """
    View to handle privacy change of a photo
    """
    photo = get_object_or_404(Photo, uuid=uuid, owner=request.user)

    if request.method == "POST":
        photo.is_private = not photo.is_private
        photo.save()
        return redirect(photo)
    
    return HttpResponseBadRequest({'error': 'Invalid request'}, status=400)


@login_required
def toggle_review(request, uuid):
    """
    Function to change review status
    review_status values:
     0 - not to be reviewed
     1 - to be reviewed
    """
    photo = get_object_or_404(Photo, uuid=uuid)

    if request.method == "POST" and (photo.owner == request.user or request.user.protector):
        if photo.review_status == 1:
            photo.review_status = 0
        else:
            photo.review_status = 1

        photo.save()
        return redirect(photo)

    return HttpResponseBadRequest({'error': 'Invalid request'}, status=400)


@login_required
def post_review(request, uuid):
    """
    View that handles posting a review
    """
    photo = get_object_or_404(Photo, uuid=uuid)
    form = PostReviewForm(request.POST)

    if request.method == "POST" and form.is_valid():
        review_object = Review.objects.create(
            owner=request.user,
            photo=photo,
            review=form.cleaned_data['review']
        )
        review_object.save()

    return redirect(photo)


@login_required
def toggle_helpful(request, review_id: int):
    """
    View that let's owner of photo mark or unmark comment as helpful
    """
    review = get_object_or_404(Review, id=review_id)

    if review.photo.owner == request.user and review.owner != request.user:
        if review.helpful:
            review.owner.score -= 1  # type: ignore
        else:
            review.owner.score += 1  # type: ignore
        review.owner.save()
        review.helpful = not review.helpful
        review.save()

    return redirect(review.photo)


@login_required
def delete_review(request, review_id: int):
    """
    View that let's post of review delete it
    """
    review = get_object_or_404(Review, id=review_id)

    if review.owner == request.user:
        review.delete()

    return redirect(review.photo)


@require_POST
@login_required
def rename_photo(request, uuid):
    """Change photo's custom name."""
    photo = get_object_or_404(Photo, uuid=uuid)
    new_name = request.POST.get('custom_name')
    if new_name not in animals_list:
        return HttpResponseBadRequest()

    if new_name and (photo.owner == request.user or request.user.protector):
        if request.user != photo.owner:
            log = Correction(
                user=request.user,
                message=f"Changed name of photo '{photo.uuid}' from '{photo.custom_name}' to '{new_name}'"
            )
            log.save()
        photo.custom_name = new_name
        photo.save()

    return redirect(photo)


@require_POST
@login_required
def set_location(request, uuid):
    if request.method == 'POST':
        photo = get_object_or_404(Photo, uuid=uuid)
        lat = request.POST.get('localization_lat')
        lng = request.POST.get('localization_lng')

        if not lat or not lng:
            return HttpResponseBadRequest({'error': 'Invalid request'}, status=400)

        lat = float(lat)
        lng = float(lng)

        if photo.owner == request.user and lat and lng:
            noisy_lat, noisy_lng = add_noise_to_localization(latitude=lat, longitude=lng)
            photo.localization_latitude = noisy_lat
            photo.localization_longitude = noisy_lng
            photo.save()
        return redirect(photo)

    return HttpResponseBadRequest({'error': 'Invalid request'}, status=400)

photo/templates/details.html
{% extends 'base.html' %}

{% block content %}
<div class="div-whole">
    <div class="card-main">
        <div class="card-inner">
            {% if prediction_1 %}
            <h2 class="card-title text-xl">{{ prediction_1 }}</h2>
            {% else %}
            <p>Wystąpił błąd podczas klasyfikacji.</p>
            {% endif %}

            <div class="flex flex-col">
                <p class="right-2 text-stone-600 text-sm self-end">{{photo.upload_time}}</p>
                <img class="my-2 rounded-xs" src="{{ photo.image.url }}" id="image" alt="Twoje zdjęcie">
            </div>

            {% if photo.owner == user %}
            <div class="flex justify-evenly w-full mb-4">
                <form method="post" action="{% url 'photo:toggle_photo_privacy' photo.uuid %}">
                    {% csrf_token %}
                    <button class='btn-second' type="submit">
                        {% if photo.is_private %}🔒 Prywatne{% else %}🔓 Publiczne{% endif %}
                    </button>
                </form>

                <form method="post" action="{% url 'photo:delete_photo' photo.uuid %}" onsubmit="return confirm('Jesteś pewien, że chcesz usunąć zdjęcie?');">
                    {% csrf_token %}
                    <button class='btn-second' type="submit">🗑️</button>
                </form>

                <form method="post" action="{% url 'photo:toggle_review' photo.uuid %}">
                    {% csrf_token %}
                    <button class='btn-second mb-4' type="submit">
                        {% if photo.review_status != 1 %}📋 Sprawdź{% else %}✅ Sprawdzone{% endif %}
                    </button>
                </form>
            </div>
            {% endif %}

            <div class="divider"></div>

            {% if photo.review_status == 0 %}
                Zdjęcie nie było sprawdzane.
            {% elif photo.review_status == 1 and photo.is_private %}
                <p style="color: red">Zdjęcie musi być publiczne, aby mogło być sprawdzone przez innych użytkowników</p>
            {% else %}
                {% if photo.review_status == 1 %}
                    <form class="mb-4" method="post" action="{% url 'photo:post_review' photo.uuid %}">
                        {% csrf_token %}
                        <fieldset class="fieldset">
                            <legend class="fieldset-legend">Właściciel zdjęcia chce twojej pomocy w weryfikacji zwierzęcia</legend>
                            {{ post_review_form }}
                        </fieldset>

                        <div class="flex justify-end">
                            <button class="btn-second" type="submit">Dodaj</button>
                        </div>
                    </form>
                {% endif %}

                {% if reviews %}
                    {% for review in reviews %}
                        <div class="review bg-base-100 shadow-md rounded-md p-4 space-y-4 border border-base-200 w-100">
                            <div class="review_upper flex justify-between items-start text-sm text-base-content">
                                <div>
                                    <span class="font-semibold">{{ review.owner.username }}</span>
                                    <span class="text-xs text-base-content/70 ml-2">{{ review.upload_time }}</span>
                                    {% if review.helpful %}
                                        <span class="ml-2 badge badge-success text-xs" title="Komentarz oznaczony, jako pomocny">✅</span>
                                    {% endif %}
                                </div>

                                <div class="flex gap-2 items-center">
                                    {% if photo.owner == user %}
                                        <form method="post" action="{% url 'photo:toggle_helpful' review.id %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-xs btn-outline btn-success ml-2">
                                                {% if review.helpful %}
                                                    ✅ Odznacz
                                                {% else %}
                                                    🟩 Pomocny
                                                {% endif %}
                                            </button>
                                        </form>
                                    {% endif %}

                                    {% if review.owner == user %}
                                        <form method="post" action="{% url 'photo:delete_review' review.id %}" onsubmit="return confirm('Jesteś pewien, że chcesz usunąć ten komentarz?');">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-xs btn-outline btn-error">
                                                🗑️
                                            </button>
                                        </form>
                                    {% endif %}
                                </div>
                            </div>

                            <div class="review_main prose max-w-none text-base">
                                {{ review.review }}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

photo/templates/upload.html
{% extends 'base.html' %}

{% block content %}
<div class="div-whole">
    <div class="card-main">
        <div class="card-inner">
            <h2 class="card-title text-xl mb-6">Wyślij zdjęcie do rozpoznania</h2>

            {% if form.errors %}
                <div id="error1" class="bg-rose-100 alert alert-error mb-4 block text-center">
                    <p class="text-lg">Wystąpił błąd w formularzu :(</p>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <p class="">❌ {{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% elif error %}
                <div id="error2" class="bg-rose-100 alert alert-error mb-4 block text-center w-fit">
                    <p class="text-error text-rose-900">{{error}}</p>
                </div>
            {% endif %}

            <form class="space-y-8" id="uploadPhotoForm" action="{% url 'photo:upload' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-control space-y-4 flex flex-col items-center">
                    <fieldset class="fieldset">
                        {{ form.image_file }}
                        <label class="label">Maksymalnie 10MB</label>
                    </fieldset>
                    <fieldset class="fieldset bg-stone-50 border-base-300 rounded-box w-fit border p-2">
                        <label class="label text-lg">
                            {{ form.is_private }}
                            Prywatne
                        </label>
                    </fieldset>
                </div>
                <button class="btn-second w-full">Wyślij</button>
            </form>
            
            <div class="text-center hidden" id="loading">
                <p style="text-aling:center">Próbuję rozpoznać zwierzaka</p>
                <span class="loading loading-ring loading-xl"></span>
            </div>
        </div>
    </div>
</div>

<script>
document.getElementById('uploadPhotoForm').addEventListener('submit', function () {
    let error1 = document.getElementById('error1');
    let error2 = document.getElementById('error2');
    if (error1 != null) {
        error1.style.display = 'none';
    }
    if (error2 != null) {
        error2.style.display = 'none';
    }
    document.getElementById('uploadPhotoForm').style.display = 'none';
    document.getElementById('loading').style.display = 'block';
})
</script>

{% endblock %}